version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: youtube-generator-timeline-ai-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - youtube-generator-timeline-ai-db:/var/lib/postgresql/data

volumes:
  youtube-generator-timeline-ai-db:
    driver: "local"
